// ========== GAUNTLET CONFIGURATION - ALL 130+ SETS ==========
const GAUNTLET_CONFIG = {
    version: "2026-06-03",
    hardBannedCards: [
        "Sol Ring",
        "Lightning Bolt",
        "Mana Crypt",
        "The Book of Exalted Deeds",
        "Celestial Unicorn",
        "Dancing Sword",
        "Dawnbringer Cleric",
        "Dragon's Disciple",
        "Guardian of Faith",
        "Icingdeath, Frost Tyrant",
        "Ingenious Smith",
        "Teleportation Circle",
        "Loyal Warhound",
        "Minimus Containment",
        "Monk of the Open Hand",
        "Oswald Fiddlebender",
        "Portable Hole",
        "Mind Flayer",
        "The Blackstaff of Waterdeep",
        "Demilich",
        "Dragon Turtle",
        "Feywild Trickster",
        "Grazilaxx, Illithid Scholar",
        "Guild Thief",
        "Iymrith, Desert Doom",
        "Asmodeus the Archfiend",
        "Wizard's Spellbook",
        "You Come to a River",
        "Lightfoot Rogue",
        "The Book of Vile Darkness",
        "Check for Traps",
        "Death-Priest of Myrkul",
        "Demogorgon's Clutches",
        "Dungeon Crawler",
        "Ebondeath, Dracolich",
        "Forsworn Paladin",
        "Gelatinous Cube",
        "Grim Bounty",
        "Grim Wanderer",
        "Battle Cry Goblin",
        "Power Word Kill",
        "Sphere of Annihilation",
        "Vorpal Sword",
        "Westgate Regent",
        "Wight",
        "Minion of the Mighty",
        "Chaos Channeler",
        "Critical Hit",
        "Delina, Wild Mage",
        "Flameskull",
        "Goblin Javelineer",
        "Hobgoblin Bandit Lord",
        "Hobgoblin Captain",
        "Hulking Bugbear",
        "Inferno of the Star Mounts",
        "Magic Missile",
        "Circle of Dreams Druid",
        "Wish",
        "Xorn",
        "Prosperous Innkeeper",
        "Froghemoth",
        "Instrument of the Bards",
        "Long Rest",
        "Lurking Roper",
        "Ochre Jelly",
        "Old Gnawbone",
        "Drizzt Do'Urden",
        "The Tarrasque",
        "Werewolf Pack Leader",
        "Adult Gold Dragon",
        "Bruenor Battlehammer",
        "The Deck of Many Things",
        "Hama Pashar, Ruin Seeker",
        "Kalain, Reclusive Painter",
        "Krydle of Baldur's Gate",
        "Minsc, Beloved Ranger",
        "Orcus, Prince of Undeath",
        "Skeletal Swarming",
        "Tiamat",
        "Trelasarra, Moon Dancer",
        "Volo, Guide to Monsters",
        "Xanathar, Guild Kingpin",
        "Treasure Chest",
        "Cave of the Frost Dragon",
        "Den of the Bugbear",
        "Hall of Storm Giants",
        "Hive of the Eye Tyrant",
        "Lair of the Hydra",
        "Treasure Vault"
    ],
    bannedCardTypes: [
        "Planeswalker",
        "Dungeon",
        "Class",
        "Saga",
        "Scheme",
        "Conspiracy"
    ],
    bannedAbilities: [
        "slivers",
        "infect",
        "venture into the dungeon"
    ],
    forceLegalCards: [],
    forceBannedCards: [],
    legalSets: [
        "Adventures in the Forgotten Realms", "Aether Revolt", "Aetherdrift", "Alara Reborn", 
        "Alliances", "Amonkhet", "Antiquities", "Apocalypse", "Arabian Nights", 
        "Assassin's Creed", "Avacyn Restored", "Battle for Zendikar", 
        "Betrayers of Kamigawa", "Bloomburrow", "Born of the Gods", "Champions of Kamigawa", 
        "Coldsnap", "Conflux", "Core Set 2019", "Core Set 2020", "Core Set 2021", 
        "Dark Ascension", "Darksteel", "Dissension", "Dominaria", "Dominaria: United", 
        "Dragons of Tarkir", "Dragon's Maze", "Duskmourn: House of Horror", "Edge of Eternities", 
        "Eldritch Moon", "Eventide", "Exodus", "Fallen Empires", "Fate Reforged", 
        "Fifth Dawn", "Final Fantasy", "Future Sight", "Gatecrash", "Guildpact", 
        "Guilds of Ravnica", "Homelands", "Hour of Devastation", "Ice Age", 
        "Ikoria: Lair of Behemoths", "Innistrad", "Innistrad: Crimson Vow", "Innistrad: Midnight Hunt", 
        "Invasion", "Ixalan", "Judgment", "Journey into Nyx", "Kaladesh", "Kaldheim", 
        "Kamigawa: Neon Dynasty", "Khans of Tarkir", "Legends", "Legions", 
        "Limited Edition Beta", "Lorwyn", "Magic 2010", "Magic 2011", "Magic 2012", 
        "Magic 2013", "Magic 2014", "Magic 2015", "Magic Origins", "March of the Machine", 
        "March of the Machine: The Aftermath", "Mercadian Masques", "Mirage", 
        "Mirrodin", "Mirrodin Besieged", "Morningtide", "The Lord of the Rings: Tales of Middle-earth", 
        "Murders at Karlov Manor", "Nemesis", "New Phyrexia", "Oath of the Gatewatch", 
        "Odyssey", "Onslaught", "Outlaws of Thunder Junction", "Phyrexia: All Will Be One", 
        "Planar Chaos", "Planeshift", "Prophecy", "Ravnica Allegiance", 
        "Ravnica: City of Guilds", "Return to Ravnica", "Rise of the Eldrazi", 
        "Rivals of Ixalan", "Saviors of Kamigawa", "Scars of Mirrodin", "Scourge", 
        "Shadows over Innistrad", "Shadowmoor", "Shards of Alara", "Streets of New Capenna", 
        "Strixhaven: School of Mages", "Stronghold", "Tarkir: Dragonstorm", "Tempest", 
        "The Brothers' War", "The Dark", "The Lost Caverns of Ixalan", "Theros", 
        "Theros Beyond Death", "Throne of Eldraine", "Time Spiral", "Torment", 
        "Urza's Destiny", "Urza's Legacy", "Urza's Saga", "Visions", 
        "War of the Spark", "Weatherlight", "Wilds of Eldraine", "Worldwake", 
        "Zendikar", "Zendikar Rising", "Modern Horizons 2"
    ],
    cashPrize: "50.00"
};
