// ========== GAUNTLET CONFIGURATION ==========
const GAUNTLET_CONFIG = {
    version: "2026.06.04.2008",
    hardBannedCards: [
    "Sol Ring",
    "Lightning Bolt",
    "Mana Crypt",
    "The Book of Exalted Deeds",
    "Celestial Unicorn",
    "Dancing Sword",
    "Dawnbringer Cleric",
    "Dragon's Disciple",
    "Guardian of Faith",
    "Icingdeath, Frost Tyrant",
    "Ingenious Smith",
    "Teleportation Circle",
    "Loyal Warhound",
    "Minimus Containment",
    "Monk of the Open Hand",
    "Oswald Fiddlebender",
    "Portable Hole",
    "Mind Flayer",
    "The Blackstaff of Waterdeep",
    "Demilich",
    "Dragon Turtle",
    "Feywild Trickster",
    "Grazilaxx, Illithid Scholar",
    "Guild Thief",
    "Iymrith, Desert Doom",
    "Asmodeus the Archfiend",
    "Wizard's Spellbook",
    "You Come to a River",
    "Lightfoot Rogue",
    "The Book of Vile Darkness",
    "Check for Traps",
    "Death-Priest of Myrkul",
    "Demogorgon's Clutches",
    "Dungeon Crawler",
    "Ebondeath, Dracolich",
    "Forsworn Paladin",
    "Gelatinous Cube",
    "Grim Bounty",
    "Grim Wanderer",
    "Battle Cry Goblin",
    "Power Word Kill",
    "Sphere of Annihilation",
    "Vorpal Sword",
    "Westgate Regent",
    "Wight",
    "Minion of the Mighty",
    "Chaos Channeler",
    "Critical Hit",
    "Delina, Wild Mage",
    "Flameskull",
    "Goblin Javelineer",
    "Hobgoblin Bandit Lord",
    "Hobgoblin Captain",
    "Hulking Bugbear",
    "Inferno of the Star Mounts",
    "Magic Missile",
    "Circle of Dreams Druid",
    "Wish",
    "Xorn",
    "Prosperous Innkeeper",
    "Froghemoth",
    "Instrument of the Bards",
    "Long Rest",
    "Lurking Roper",
    "Ochre Jelly",
    "Old Gnawbone",
    "Drizzt Do'Urden",
    "The Tarrasque",
    "Werewolf Pack Leader",
    "Adult Gold Dragon",
    "Bruenor Battlehammer",
    "The Deck of Many Things",
    "Hama Pashar, Ruin Seeker",
    "Kalain, Reclusive Painter",
    "Krydle of Baldur's Gate",
    "Minsc, Beloved Ranger",
    "Orcus, Prince of Undeath",
    "Skeletal Swarming",
    "Tiamat",
    "Trelasarra, Moon Dancer",
    "Volo, Guide to Monsters",
    "Xanathar, Guild Kingpin",
    "Treasure Chest",
    "Cave of the Frost Dragon",
    "Den of the Bugbear",
    "Hall of Storm Giants",
    "Hive of the Eye Tyrant",
    "Lair of the Hydra",
    "Treasure Vault",
    "Mox Ruby",
    "Forcefield",
    "Gauntlet of Might",
    "Howling Mine",
    "Icy Manipulator",
    "Illusionary Mask",
    "Mana Vault",
    "Mox Emerald",
    "Mox Jet",
    "Mox Pearl",
    "Volcanic Island",
    "Mox Sapphire",
    "Time Vault",
    "Winter Orb",
    "Badlands",
    "Bayou",
    "Plateau",
    "Savannah",
    "Scrubland",
    "Taiga",
    "Tropical Island",
    "Tundra",
    "Underground Sea",
    "Balance",
    "Circle of Protection: Black",
    "Circle of Protection: Blue",
    "Circle of Protection: Green",
    "Circle of Protection: Red",
    "Circle of Protection: White",
    "Ancestral Recall",
    "Island Sanctuary",
    "Karma",
    "Savannah Lions",
    "Swords to Plowshares",
    "Power Sink",
    "Braingeyser",
    "Control Magic",
    "Copy Artifact",
    "Lord of Atlantis",
    "Mana Short",
    "Stasis",
    "Time Walk",
    "Timetwister",
    "Bad Moon",
    "Dark Ritual",
    "Demonic Tutor",
    "Hypnotic Specter",
    "Lich",
    "Mind Twist",
    "Nether Shadow",
    "Word of Command",
    "Earthquake",
    "Fork",
    "Goblin King",
    "Manabarbs",
    "Raging River",
    "Fastbond",
    "Wheel of Fortune",
    "Berserk",
    "Birds of Paradise",
    "Regrowth",
    "Llanowar Elves",
    "Black Vise",
    "Verduran Enchantress",
    "Ankh of Mishra",
    "Basalt Monolith",
    "Kormus Bell",
    "Baneslayer Angel",
    "Captain of the Watch",
    "Elite Vanguard",
    "Guardian Seraph",
    "Harm's Way",
    "Honor of the Pure",
    "Mesa Enchantress",
    "Open the Vaults",
    "Silence",
    "Ponder",
    "Fabricate",
    "Hive Mind",
    "Merfolk Looter",
    "Merfolk Sovereign",
    "Mind Spring",
    "Duress",
    "Sphinx Ambassador",
    "Time Warp",
    "Twincast",
    "Cemetery Reaper",
    "Vampire Nocturnus",
    "Mind Shatter",
    "Underworld Dreams",
    "Jackal Familiar",
    "Xathrid Demon",
    "Ball Lightning",
    "Bogardan Hellkite",
    "Goblin Chieftain",
    "Ant Queen",
    "Magma Phoenix",
    "Pyroclasm",
    "Siege-Gang Commander",
    "Acidic Slime",
    "Master of the Wild Hunt",
    "Elvish Archdruid",
    "Ornithopter",
    "Overrun",
    "Protean Hydra",
    "Darksteel Colossus",
    "Gorgon Flail",
    "Sunpetal Grove",
    "Platinum Angel",
    "Dragonskull Summit",
    "Drowned Catacomb",
    "Gargoyle Castle",
    "Glacial Fortress",
    "Rootbound Crag",
    "Soltari Champion",
    "Mana Leak",
    "Stronghold Taskmaster",
    "Bottomless Pit",
    "Grave Pact",
    "Tortured Existence",
    "Fling",
    "Mogg Flunkies",
    "Shard Phoenix",
    "Mulch",
    "Hermit Druid",
    "Spike Feeder",
    "Volrath's Stronghold",
    "Wall of Blossoms",
    "Sliver Queen",
    "Spined Sliver",
    "Ensnaring Bridge",
    "Horn of Greed",
    "Aethergeode Miner",
    "Call for Unity",
    "Exquisite Archangel",
    "Restoration Specialist",
    "Solemn Recruit",
    "Sram, Senior Edificer",
    "Sram's Expertise",
    "Trophy Mage",
    "Thopter Arrest",
    "Aethertide Whale",
    "Baral, Chief of Compliance",
    "Baral's Expertise",
    "Efficient Construction",
    "Secret Salvage",
    "Whir of Invention",
    "Gifted Aetherborn",
    "Glint-Sleeve Siphoner",
    "Herald of Anguish",
    "Midnight Entourage",
    "Release the Gremlins",
    "Yahenni, Undying Partisan",
    "Yahenni's Expertise",
    "Indomitable Creativity",
    "Kari Zev, Skyship Raider",
    "Kari Zev's Expertise",
    "Pia's Revolution",
    "Narnam Renegade",
    "Wrangle",
    "Aetherwind Basker",
    "Aid from the Cowl",
    "Greenwheel Liberator",
    "Aethersphere Harvester",
    "Rishkar, Peema Renegade",
    "Rishkar's Expertise",
    "Dark Intimations",
    "Hidden Stockpile",
    "Oath of Ajani",
    "Renegade Rallier",
    "Winding Constrictor",
    "Metallic Mimic",
    "Gonti's Aether Heart",
    "Heart of Kiran",
    "Hope of Ghirapur",
    "Inspiring Statuary",
    "Lifecrafter's Bestiary",
    "Merchant's Dockhand",
    "Spire of Industry",
    "Paradox Engine",
    "Peacewalker Colossus",
    "Planar Bridge",
    "Scrap Trawler",
    "Untethered Express",
    "Walking Ballista",
    "Air Response Unit",
    "Guardian Sunmare",
    "Nesting Bot",
    "Perilous Snare",
    "Keen Buccaneer",
    "Ride's End",
    "Salvation Engine",
    "Skyseer's Chariot",
    "Sundial, Dawn Tyrant",
    "Valor's Flagship",
    "Voyager Glidecar",
    "Voyager Quickwelder",
    "Aether Syphon",
    "Unstoppable Plan",
    "Mindspring Merfolk",
    "Mu Yanling, Wind Rider",
    "Possession Engine",
    "Rangers' Refueler",
    "Repurposing Bay",
    "Riverchurn Monument",
    "Scrounging Skyray",
    "Stock Up",
    "Thopter Fabricator",
    "Transit Mage",
    "The Last Ride",
    "Vnwxt, Verbose Host",
    "Waxen Shapethief",
    "Bloodghast",
    "Cryptcaller Chariot",
    "Cursecloth Wrappings",
    "Demonic Junker",
    "Gas Guzzler",
    "Gonti, Night Minister",
    "Intimidation Tactics",
    "Daretti, Rocketeer Engineer",
    "Momentum Breaker",
    "Quag Feast",
    "The Speed Demon",
    "Wretched Doll",
    "Adrenaline Jockey",
    "Boommobile",
    "Burnout Bashtronaut",
    "Count on Luck",
    "Push the Limit",
    "Draconautics Engineer",
    "Full Throttle",
    "Gastal Thrillroller",
    "Greasewrench Goblin",
    "Hazoret, Godseeker",
    "Howlsquad Heavy",
    "Magmakin Artillerist",
    "Marauding Mako",
    "Pacesetter Paragon",
    "Lumbering Worldwagon",
    "Spire Mechcycle",
    "Tyrox, Saurid Tyrant",
    "Afterburner Expert",
    "Agonasaur Rex",
    "District Mascot",
    "Earthrumbler",
    "Elvish Refueler",
    "Brightglass Gearhulk",
    "March of the World Ooze",
    "Oviya, Automech Artisan",
    "Point the Way",
    "Regal Imperiosaur",
    "Rise from the Wreck",
    "Run Over",
    "Terrian, World Tyrant",
    "Thunderous Velocipede",
    "Webstrike Elite",
    "Aatchik, Emerald Radian",
    "Apocalypse Runner",
    "Boom Scholar",
    "Boosted Sloop",
    "Pyrewood Gearhulk",
    "Broodheart Engine",
    "Captain Howler, Sea Scourge",
    "Caradora, Heart of Alacria",
    "Cloudspire Coordinator",
    "Coalstoke Gearhulk",
    "Debris Beetle",
    "Dune Drifter",
    "Embalmed Ascendant",
    "Explosive Getaway",
    "Far Fortune, End Boss",
    "Fearless Swashbuckler",
    "Gastal Thrillseeker",
    "Haunt the Network",
    "Ketramose, the New Dawn",
    "Kolodin, Triumph Caster",
    "Lagorin, Soul of Alacria",
    "Loot, the Pathfinder",
    "Mendicant Core, Guidelight",
    "Mimeoplasm, Revered One",
    "Oildeep Gearhulk",
    "Radiant Lotus",
    "Rangers' Aetherhive",
    "Redshift, Rocketeer Chief",
    "Riptide Gearhulk",
    "Sab-Sunen, Luxa Embodied",
    "Samut, the Driving Force",
    "Sita Varma, Masked Racer",
    "Skyserpent Seeker",
    "Veteran Beastrider",
    "Winter, Cursed Rider",
    "Zahur, Glory's Past",
    "Lifecraft Engine",
    "Marketback Walker",
    "Monument to Endurance",
    "Sunbillow Verge",
    "Bleachbone Verge",
    "Bloodfell Caves",
    "Blossoming Sands",
    "Dismal Backwater",
    "Jungle Hollow",
    "Muraganda Raceway",
    "Riverpyre Verge",
    "Rugged Highlands",
    "Scoured Barrens",
    "Night Market",
    "Wind-Scarred Crag",
    "Swiftwater Cliffs",
    "Thornwood Falls",
    "Tranquil Cove",
    "Wastewood Verge",
    "Willowrush Verge",
    "Aven Mimeomancer",
    "Meddling Mage",
    "Sovereigns of Lost Alara",
    "Lich Lord of Unx",
    "Thought Hemorrhage",
    "Nemesis of Reason",
    "Time Sieve",
    "Defiler of Souls",
    "Knotvine Paladin",
    "Blitz Hellion",
    "Dragon Broodmother",
    "Spellbreaker Behemoth",
    "Behemoth Sledge",
    "Dauntless Escort",
    "Knight of New Alara",
    "Cerodon Yearling",
    "Qasali Pridemage",
    "Sigil Captain",
    "Zealous Persecution",
    "Cloven Casting",
    "Double Negative",
    "Lord of Extinction",
    "Maelstrom Pulse",
    "Putrid Leech",
    "Lorescale Coatl",
    "Nulltread Gargantuan",
    "Sages of the Anima",
    "Vedalken Heretic",
    "Winged Coatl",
    "Sen Triplets",
    "Sphinx of the Steel Wind",
    "Thraximundar",
    "Karrthus, Tyrant of Jund",
    "Naya Hushblade",
    "Mayael's Aria",
    "Retaliator Griffin",
    "Finest Hour",
    "Jenara, Asura of War",
    "Thopter Foundry",
    "Force of Will",
    "Contagion",
    "Pyrokinesis",
    "Bounty of the Hunt",
    "Elvish Spirit Guide",
    "Lim-Dûl's Vault",
    "Yavimaya Ants",
    "Thawing Glaciers",
    "Shield Sphere",
    "Kjeldoran Outpost",
    "Lake of the Dead",
    "Angel of Sanctions",
    "Anointed Procession",
    "Approach of the Second Sun",
    "Aven Mindcensor",
    "Cast Out",
    "Gideon's Intervention",
    "Glory-Bound Initiate",
    "Oketra the True",
    "Regal Caracal",
    "Trial of Solidarity",
    "As Foretold",
    "Pull from Tomorrow",
    "Curator of Mysteries",
    "Drake Haven",
    "Glyph Keeper",
    "Kefnet the Mindful",
    "New Perspectives",
    "Open into Wonder",
    "Lay Bare the Heart",
    "Trial of Knowledge",
    "Vizier of Many Faces",
    "Winds of Rebuke",
    "Archfiend of Ifnir",
    "Baleful Ammit",
    "Bone Picker",
    "Bontu the Glorified",
    "Dread Wanderer",
    "Faith of the Devoted",
    "Ahn-Crop Crasher",
    "Liliana's Mastery",
    "Lord of the Accursed",
    "Plague Belcher",
    "Shadow of the Grave",
    "Heart-Piercer Manticore",
    "Bloodrage Brawler",
    "Combat Celebrant",
    "Flameblade Adept",
    "Glorybringer",
    "Hazoret the Fervent",
    "Exemplar of Strength",
    "Soul-Scar Mage",
    "Sweltering Suns",
    "Trial of Zeal",
    "Crocodile of the Crossing",
    "Champion of Rhonas",
    "Defiant Greatmaw",
    "Channeler Initiate",
    "Vizier of the Menagerie",
    "Harvest Season",
    "Honored Hydra",
    "Manglehorn",
    "Prowling Serpopard",
    "Rhonas the Indomitable",
    "Sandwurm Convergence",
    "Trial of Strength",
    "Start // Finish",
    "Ahn-Crop Champion",
    "Bounty of the Luxa",
    "Enigma Drake",
    "Hapatra, Vizier of Poisons",
    "Honored Crop-Captain",
    "Khenra Charioteer",
    "Neheb, the Worthy",
    "Samut, Voice of Dissent",
    "Temmet, Vizier of Naktamun",
    "Wayward Servant",
    "Dusk // Dawn",
    "Commit // Memory",
    "Never // Return",
    "Insult // Injury",
    "Reduce // Rubble",
    "Mouth // Feed",
    "Cascading Cataracts",
    "Destined // Lead",
    "Onward // Victory",
    "Spring // Mind",
    "Prepare // Fight",
    "Failure // Comply",
    "Rags // Riches",
    "Bontu's Monument",
    "Cut // Ribbons",
    "Heaven // Earth",
    "Gate to the Afterlife",
    "Hazoret's Monument",
    "Kefnet's Monument",
    "Oketra's Monument",
    "Oracle's Vault",
    "Rhonas's Monument",
    "Throne of the God-Pharaoh",
    "Canyon Slough",
    "Gideon's Resolve",
    "Fetid Pools",
    "Irrigated Farmland",
    "Scattered Groves",
    "Sheltered Thicket",
    "Transmute Artifact",
    "Candelabra of Tawnos",
    "Titania's Song",
    "Ashnod's Altar",
    "The Rack",
    "Ivory Tower",
    "Su-Chi",
    "Urza's Tower",
    "Triskelion",
    "Mishra's Factory",
    "Mishra's Workshop",
    "Urza's Mine",
    "Urza's Power Plant",
    "Ambassador Laquatus",
    "Aquamoeba",
    "Breakthrough",
    "Circular Logic",
    "Compulsion",
    "Mind Sludge",
    "Cabal Ritual",
    "Chainer's Edict",
    "Ichorid",
    "Laquatus's Champion",
    "Mesmeric Fiend",
    "Mutilate",
    "Nantuko Shade",
    "Devastating Dreams",
    "Arrogant Wurm",
    "Fiery Temper",
    "Grim Lavamancer",
    "Cabal Coffers",
    "Basking Rootwalla",
    "Spectral Lynx",
    "Ice Cave",
    "Phyrexian Arena",
    "Whirlpool Warrior",
    "Goblin Ringleader",
    "Death Grasp",
    "Urborg Elf",
    "Fervent Charge",
    "Gerrard's Verdict",
    "Goblin Legionnaire",
    "Goblin Trenches",
    "Guided Passage",
    "Last Stand",
    "Lightning Angel",
    "Minotaur Illusionist",
    "Mystic Snake",
    "Pernicious Deed",
    "Powerstone Minefield",
    "Prophetic Bolt",
    "Yavimaya Coast",
    "Spiritmonger",
    "Fire // Ice",
    "Illusion // Reality",
    "Life // Death",
    "Night // Day",
    "Order // Chaos",
    "Dragon Arch",
    "Legacy Weapon",
    "Battlefield Forge",
    "Caves of Koilos",
    "Llanowar Wastes",
    "Shivan Reef",
    "Shahrazad",
    "Old Man of the Sea",
    "Serendib Efreet",
    "Drop of Honey",
    "Juzám Djinn",
    "Kird Ape",
    "Diamond Valley",
    "Ring of Ma'rûf",
    "Bazaar of Baghdad",
    "City of Brass",
    "Library of Alexandria",
    "Island of Wak-Wak"
],
    bannedCardTypes: [
    "Planeswalker",
    "Dungeon",
    "Class",
    "Saga",
    "Scheme",
    "Conspiracy"
],
    bannedAbilities: [
    "slivers",
    "infect",
    "venture into the dungeon",
    "ante",
    "hexproof",
    "cascade"
],
    forceLegalCards: [
    "Siren's Call",
    "Disenchant",
    "Psychic Venom",
    "Spell Blast",
    "Steal Artifact",
    "Animate Wall",
    "Black Ward",
    "Blessing",
    "Blue Ward",
    "Consecrate Land",
    "Farmstead",
    "Green Ward",
    "Holy Armor",
    "Holy Strength",
    "Animate Artifact",
    "Lance",
    "Red Ward",
    "White Ward",
    "Power Leak",
    "Creature Bond",
    "Feedback",
    "Invisibility",
    "Flight",
    "Phantasmal Terrain",
    "Cursed Land",
    "Evil Presence",
    "Fear",
    "Paralyze",
    "Burrowing",
    "Unholy Strength",
    "Warp Artifact",
    "Weakness",
    "Earthbind",
    "Firebreathing",
    "Flashfires",
    "Shatter",
    "Tunnel",
    "Aspect of Wolf",
    "Instill Energy",
    "Lure",
    "Regeneration",
    "Tranquility",
    "Tsunami",
    "Wanderlust",
    "Web",
    "Wild Growth",
    "Armored Ascension",
    "Divine Verdict",
    "Indestructibility",
    "Lifelink",
    "Pacifism",
    "Convincing Mirage",
    "Solemn Offering",
    "Tempest of Light",
    "Essence Scatter",
    "Flashfreeze",
    "Ice Cage",
    "Negate",
    "Assassinate",
    "Deathmark",
    "Soul Bleed",
    "Ignite Disorder",
    "Entangling Vines",
    "Naturalize",
    "Oakenform",
    "Calming Licid",
    "Conviction",
    "Samite Blessing",
    "Smite",
    "Contempt",
    "Gliding Licid",
    "Corrupting Licid",
    "Death Stroke",
    "Mogg Infestation",
    "Torment",
    "Convulsing Licid",
    "Flowstone Blade",
    "Tempting Licid",
    "Aerial Modification",
    "Caught in the Brights",
    "Decommission",
    "Ice Over",
    "Gremlin Infestation",
    "Siege Modification",
    "Lightwheel Enhancements",
    "Roadside Assistance",
    "Flood the Engine",
    "Guidelight Optimizer",
    "Crash and Burn",
    "Skycrash",
    "Plow Through",
    "Silken Strength",
    "Ticket Tortoise",
    "Ardent Plea",
    "Stormcaller's Boon",
    "Soul Manipulation",
    "Soul Manipulation",
    "Demonic Dread",
    "Violent Outburst",
    "Captured Sunlight",
    "Magefire Wings",
    "Kjeldoran Pride",
    "Awesome Presence",
    "Diseased Vermin",
    "False Demise",
    "Suffocation",
    "Viscerid Armor",
    "Casting of Bones",
    "Bestial Fury",
    "Krovikan Plague",
    "Phyrexian Boon",
    "Gift of the Woods",
    "Veteran's Voice",
    "Nature's Chosen",
    "Cartouche of Solidarity",
    "Compulsory Rest",
    "Impeccable Timing",
    "Cartouche of Knowledge",
    "Illusory Wrappings",
    "Lay Claim",
    "Cartouche of Ambition",
    "Trespasser's Curse",
    "Cartouche of Zeal",
    "Deem Worthy",
    "Violent Impact",
    "Cartouche of Strength",
    "Dissenter's Deliverance",
    "Sixth Sense",
    "Artifact Ward",
    "Artifact Possession",
    "Artifact Blast",
    "Crumble",
    "Cleansing Meditation",
    "Floating Shield",
    "Frantic Purification",
    "Major Teroh",
    "Morningtide",
    "Stupefying Touch",
    "Coral Net",
    "Ghostly Wings",
    "Liquify",
    "Shade's Form",
    "Crackling Club",
    "Skullscorch",
    "Sonic Seizure",
    "Coalition Flag",
    "Manacles of Decay",
    "Orim's Thunder",
    "Shield of Duty and Reason",
    "Foul Presence",
    "Smash",
    "Bloodfire Infusion",
    "Desolation Giant",
    "Tranquil Path",
    "Quicksilver Dagger",
    "Squee's Embrace",
    "Yavimaya's Embrace",
    "Abu Ja'far",
    "Fishliver Oil"
],
    forceBannedCards: [],
    legalSets: [
    "Adventures in the Forgotten Realms",
    "Aether Revolt",
    "Aetherdrift",
    "Alara Reborn",
    "Alliances",
    "Amonkhet",
    "Antiquities",
    "Apocalypse",
    "Arabian Nights",
    "Assassin's Creed",
    "Avacyn Restored",
    "Battle for Zendikar",
    "Betrayers of Kamigawa",
    "Bloomburrow",
    "Born of the Gods",
    "Champions of Kamigawa",
    "Coldsnap",
    "Conflux",
    "Core Set 2019",
    "Core Set 2020",
    "Core Set 2021",
    "Dark Ascension",
    "Darksteel",
    "Dissension",
    "Dominaria",
    "Dominaria: United",
    "Dragon's Maze",
    "Dragons of Tarkir",
    "Duskmourn: House of Horror",
    "Edge of Eternities",
    "Eldritch Moon",
    "Eventide",
    "Exodus",
    "Fallen Empires",
    "Fate Reforged",
    "Fifth Dawn",
    "Final Fantasy",
    "Future Sight",
    "Gatecrash",
    "Guildpact",
    "Guilds of Ravnica",
    "Homelands",
    "Hour of Devastation",
    "Ice Age",
    "Ikoria: Lair of Behemoths",
    "Innistrad",
    "Innistrad: Crimson Vow",
    "Innistrad: Midnight Hunt",
    "Invasion",
    "Ixalan",
    "Journey into Nyx",
    "Judgment",
    "Kaladesh",
    "Kaldheim",
    "Kamigawa: Neon Dynasty",
    "Khans of Tarkir",
    "Legends",
    "Legions",
    "Limited Edition Beta",
    "Lorwyn",
    "Magic 2010",
    "Magic 2011",
    "Magic 2012",
    "Magic 2013",
    "Magic 2014",
    "Magic 2015",
    "Magic Origins",
    "March of the Machine",
    "March of the Machine: The Aftermath",
    "Mercadian Masques",
    "Mirage",
    "Mirrodin",
    "Mirrodin Besieged",
    "Modern Horizons 2",
    "Morningtide",
    "Murders at Karlov Manor",
    "Nemesis",
    "New Phyrexia",
    "Oath of the Gatewatch",
    "Odyssey",
    "Onslaught",
    "Outlaws of Thunder Junction",
    "Phyrexia: All Will Be One",
    "Planar Chaos",
    "Planeshift",
    "Prophecy",
    "Ravnica Allegiance",
    "Ravnica: City of Guilds",
    "Return to Ravnica",
    "Rise of the Eldrazi",
    "Rivals of Ixalan",
    "Saviors of Kamigawa",
    "Scars of Mirrodin",
    "Scourge",
    "Shadowmoor",
    "Shadows over Innistrad",
    "Shards of Alara",
    "Streets of New Capenna",
    "Strixhaven: School of Mages",
    "Stronghold",
    "Tarkir: Dragonstorm",
    "Tempest",
    "The Brothers' War",
    "The Dark",
    "The Lord of the Rings: Tales of Middle-earth",
    "The Lost Caverns of Ixalan",
    "Theros",
    "Theros Beyond Death",
    "Throne of Eldraine",
    "Time Spiral",
    "Torment",
    "Urza's Destiny",
    "Urza's Legacy",
    "Urza's Saga",
    "Visions",
    "War of the Spark",
    "Weatherlight",
    "Wilds of Eldraine",
    "Worldwake",
    "Zendikar",
    "Zendikar Rising"
],
    cashPrize: "50.00"
};

// ⭐ MAKE IT GLOBALLY ACCESSIBLE ⭐
if (typeof window !== 'undefined') {
    window.GAUNTLET_CONFIG = GAUNTLET_CONFIG;
        }
