// ========== GAUNTLET CONFIGURATION ==========
const GAUNTLET_CONFIG = {
    version: "2026.06.04.1327",
    hardBannedCards: [
    "Sol Ring",
    "Lightning Bolt",
    "Mana Crypt",
    "The Book of Exalted Deeds",
    "Celestial Unicorn",
    "Dancing Sword",
    "Dawnbringer Cleric",
    "Dragon's Disciple",
    "Guardian of Faith",
    "Icingdeath, Frost Tyrant",
    "Ingenious Smith",
    "Teleportation Circle",
    "Loyal Warhound",
    "Minimus Containment",
    "Monk of the Open Hand",
    "Oswald Fiddlebender",
    "Portable Hole",
    "Mind Flayer",
    "The Blackstaff of Waterdeep",
    "Demilich",
    "Dragon Turtle",
    "Feywild Trickster",
    "Grazilaxx, Illithid Scholar",
    "Guild Thief",
    "Iymrith, Desert Doom",
    "Asmodeus the Archfiend",
    "Wizard's Spellbook",
    "You Come to a River",
    "Lightfoot Rogue",
    "The Book of Vile Darkness",
    "Check for Traps",
    "Death-Priest of Myrkul",
    "Demogorgon's Clutches",
    "Dungeon Crawler",
    "Ebondeath, Dracolich",
    "Forsworn Paladin",
    "Gelatinous Cube",
    "Grim Bounty",
    "Grim Wanderer",
    "Battle Cry Goblin",
    "Power Word Kill",
    "Sphere of Annihilation",
    "Vorpal Sword",
    "Westgate Regent",
    "Wight",
    "Minion of the Mighty",
    "Chaos Channeler",
    "Critical Hit",
    "Delina, Wild Mage",
    "Flameskull",
    "Goblin Javelineer",
    "Hobgoblin Bandit Lord",
    "Hobgoblin Captain",
    "Hulking Bugbear",
    "Inferno of the Star Mounts",
    "Magic Missile",
    "Circle of Dreams Druid",
    "Wish",
    "Xorn",
    "Prosperous Innkeeper",
    "Froghemoth",
    "Instrument of the Bards",
    "Long Rest",
    "Lurking Roper",
    "Ochre Jelly",
    "Old Gnawbone",
    "Drizzt Do'Urden",
    "The Tarrasque",
    "Werewolf Pack Leader",
    "Adult Gold Dragon",
    "Bruenor Battlehammer",
    "The Deck of Many Things",
    "Hama Pashar, Ruin Seeker",
    "Kalain, Reclusive Painter",
    "Krydle of Baldur's Gate",
    "Minsc, Beloved Ranger",
    "Orcus, Prince of Undeath",
    "Skeletal Swarming",
    "Tiamat",
    "Trelasarra, Moon Dancer",
    "Volo, Guide to Monsters",
    "Xanathar, Guild Kingpin",
    "Treasure Chest",
    "Cave of the Frost Dragon",
    "Den of the Bugbear",
    "Hall of Storm Giants",
    "Hive of the Eye Tyrant",
    "Lair of the Hydra",
    "Treasure Vault",
    "Mox Ruby",
    "Forcefield",
    "Gauntlet of Might",
    "Howling Mine",
    "Icy Manipulator",
    "Illusionary Mask",
    "Mana Vault",
    "Mox Emerald",
    "Mox Jet",
    "Mox Pearl",
    "Volcanic Island",
    "Mox Sapphire",
    "Time Vault",
    "Winter Orb",
    "Badlands",
    "Bayou",
    "Plateau",
    "Savannah",
    "Scrubland",
    "Taiga",
    "Tropical Island",
    "Tundra",
    "Underground Sea",
    "Balance",
    "Circle of Protection: Black",
    "Circle of Protection: Blue",
    "Circle of Protection: Green",
    "Circle of Protection: Red",
    "Circle of Protection: White",
    "Ancestral Recall",
    "Island Sanctuary",
    "Karma",
    "Savannah Lions",
    "Swords to Plowshares",
    "Power Sink",
    "Braingeyser",
    "Control Magic",
    "Copy Artifact",
    "Lord of Atlantis",
    "Mana Short",
    "Stasis",
    "Time Walk",
    "Timetwister",
    "Bad Moon",
    "Dark Ritual",
    "Demonic Tutor",
    "Hypnotic Specter",
    "Lich",
    "Mind Twist",
    "Nether Shadow",
    "Word of Command",
    "Earthquake",
    "Fork",
    "Goblin King",
    "Manabarbs",
    "Raging River",
    "Fastbond",
    "Wheel of Fortune",
    "Berserk",
    "Birds of Paradise",
    "Regrowth",
    "Llanowar Elves",
    "Black Vise",
    "Verduran Enchantress",
    "Ankh of Mishra",
    "Basalt Monolith",
    "Kormus Bell",
    "Baneslayer Angel",
    "Captain of the Watch",
    "Elite Vanguard",
    "Guardian Seraph",
    "Harm's Way",
    "Honor of the Pure",
    "Mesa Enchantress",
    "Open the Vaults",
    "Silence",
    "Ponder",
    "Fabricate",
    "Hive Mind",
    "Merfolk Looter",
    "Merfolk Sovereign",
    "Mind Spring",
    "Duress",
    "Sphinx Ambassador",
    "Time Warp",
    "Twincast",
    "Cemetery Reaper",
    "Vampire Nocturnus",
    "Mind Shatter",
    "Underworld Dreams",
    "Jackal Familiar",
    "Xathrid Demon",
    "Ball Lightning",
    "Bogardan Hellkite",
    "Goblin Chieftain",
    "Ant Queen",
    "Magma Phoenix",
    "Pyroclasm",
    "Siege-Gang Commander",
    "Acidic Slime",
    "Master of the Wild Hunt",
    "Elvish Archdruid",
    "Ornithopter",
    "Overrun",
    "Protean Hydra",
    "Darksteel Colossus",
    "Gorgon Flail",
    "Sunpetal Grove",
    "Platinum Angel",
    "Dragonskull Summit",
    "Drowned Catacomb",
    "Gargoyle Castle",
    "Glacial Fortress",
    "Rootbound Crag",
    "Soltari Champion",
    "Mana Leak",
    "Stronghold Taskmaster",
    "Bottomless Pit",
    "Grave Pact",
    "Tortured Existence",
    "Fling",
    "Mogg Flunkies",
    "Shard Phoenix",
    "Mulch",
    "Hermit Druid",
    "Spike Feeder",
    "Volrath's Stronghold",
    "Wall of Blossoms",
    "Sliver Queen",
    "Spined Sliver",
    "Ensnaring Bridge",
    "Horn of Greed",
    "Aethergeode Miner",
    "Call for Unity",
    "Exquisite Archangel",
    "Restoration Specialist",
    "Solemn Recruit",
    "Sram, Senior Edificer",
    "Sram's Expertise",
    "Trophy Mage",
    "Thopter Arrest",
    "Aethertide Whale",
    "Baral, Chief of Compliance",
    "Baral's Expertise",
    "Efficient Construction",
    "Secret Salvage",
    "Whir of Invention",
    "Gifted Aetherborn",
    "Glint-Sleeve Siphoner",
    "Herald of Anguish",
    "Midnight Entourage",
    "Release the Gremlins",
    "Yahenni, Undying Partisan",
    "Yahenni's Expertise",
    "Indomitable Creativity",
    "Kari Zev, Skyship Raider",
    "Kari Zev's Expertise",
    "Pia's Revolution",
    "Narnam Renegade",
    "Wrangle",
    "Aetherwind Basker",
    "Aid from the Cowl",
    "Greenwheel Liberator",
    "Aethersphere Harvester",
    "Rishkar, Peema Renegade",
    "Rishkar's Expertise",
    "Dark Intimations",
    "Hidden Stockpile",
    "Oath of Ajani",
    "Renegade Rallier",
    "Winding Constrictor",
    "Metallic Mimic",
    "Gonti's Aether Heart",
    "Heart of Kiran",
    "Hope of Ghirapur",
    "Inspiring Statuary",
    "Lifecrafter's Bestiary",
    "Merchant's Dockhand",
    "Spire of Industry",
    "Paradox Engine",
    "Peacewalker Colossus",
    "Planar Bridge",
    "Scrap Trawler",
    "Untethered Express",
    "Walking Ballista",
    "Air Response Unit",
    "Guardian Sunmare",
    "Nesting Bot",
    "Perilous Snare",
    "Keen Buccaneer",
    "Ride's End",
    "Salvation Engine",
    "Skyseer's Chariot",
    "Sundial, Dawn Tyrant",
    "Valor's Flagship",
    "Voyager Glidecar",
    "Voyager Quickwelder",
    "Aether Syphon",
    "Unstoppable Plan",
    "Mindspring Merfolk",
    "Mu Yanling, Wind Rider",
    "Possession Engine",
    "Rangers' Refueler",
    "Repurposing Bay",
    "Riverchurn Monument",
    "Scrounging Skyray",
    "Stock Up",
    "Thopter Fabricator",
    "Transit Mage",
    "The Last Ride",
    "Vnwxt, Verbose Host",
    "Waxen Shapethief",
    "Bloodghast",
    "Cryptcaller Chariot",
    "Cursecloth Wrappings",
    "Demonic Junker",
    "Gas Guzzler",
    "Gonti, Night Minister",
    "Intimidation Tactics",
    "Daretti, Rocketeer Engineer",
    "Momentum Breaker",
    "Quag Feast",
    "The Speed Demon",
    "Wretched Doll",
    "Adrenaline Jockey",
    "Boommobile",
    "Burnout Bashtronaut",
    "Count on Luck",
    "Push the Limit",
    "Draconautics Engineer",
    "Full Throttle",
    "Gastal Thrillroller",
    "Greasewrench Goblin",
    "Hazoret, Godseeker",
    "Howlsquad Heavy",
    "Magmakin Artillerist",
    "Marauding Mako",
    "Pacesetter Paragon",
    "Lumbering Worldwagon",
    "Spire Mechcycle",
    "Tyrox, Saurid Tyrant",
    "Afterburner Expert",
    "Agonasaur Rex",
    "District Mascot",
    "Earthrumbler",
    "Elvish Refueler",
    "Brightglass Gearhulk",
    "March of the World Ooze",
    "Oviya, Automech Artisan",
    "Point the Way",
    "Regal Imperiosaur",
    "Rise from the Wreck",
    "Run Over",
    "Terrian, World Tyrant",
    "Thunderous Velocipede",
    "Webstrike Elite",
    "Aatchik, Emerald Radian",
    "Apocalypse Runner",
    "Boom Scholar",
    "Boosted Sloop",
    "Pyrewood Gearhulk",
    "Broodheart Engine",
    "Captain Howler, Sea Scourge",
    "Caradora, Heart of Alacria",
    "Cloudspire Coordinator",
    "Coalstoke Gearhulk",
    "Debris Beetle",
    "Dune Drifter",
    "Embalmed Ascendant",
    "Explosive Getaway",
    "Far Fortune, End Boss",
    "Fearless Swashbuckler",
    "Gastal Thrillseeker",
    "Haunt the Network",
    "Ketramose, the New Dawn",
    "Kolodin, Triumph Caster",
    "Lagorin, Soul of Alacria",
    "Loot, the Pathfinder",
    "Mendicant Core, Guidelight",
    "Mimeoplasm, Revered One",
    "Oildeep Gearhulk",
    "Radiant Lotus",
    "Rangers' Aetherhive",
    "Redshift, Rocketeer Chief",
    "Riptide Gearhulk",
    "Sab-Sunen, Luxa Embodied",
    "Samut, the Driving Force",
    "Sita Varma, Masked Racer",
    "Skyserpent Seeker",
    "Veteran Beastrider",
    "Winter, Cursed Rider",
    "Zahur, Glory's Past",
    "Lifecraft Engine",
    "Marketback Walker",
    "Monument to Endurance",
    "Sunbillow Verge",
    "Bleachbone Verge",
    "Bloodfell Caves",
    "Blossoming Sands",
    "Dismal Backwater",
    "Jungle Hollow",
    "Muraganda Raceway",
    "Riverpyre Verge",
    "Rugged Highlands",
    "Scoured Barrens",
    "Night Market",
    "Wind-Scarred Crag",
    "Swiftwater Cliffs",
    "Thornwood Falls",
    "Tranquil Cove",
    "Wastewood Verge",
    "Willowrush Verge"
],
    bannedCardTypes: [
    "Planeswalker",
    "Dungeon",
    "Class",
    "Saga",
    "Scheme",
    "Conspiracy"
],
    bannedAbilities: [
    "slivers",
    "infect",
    "venture into the dungeon",
    "ante",
    "hexproof"
],
    forceLegalCards: [
    "Siren's Call",
    "Disenchant",
    "Psychic Venom",
    "Spell Blast",
    "Steal Artifact",
    "Animate Wall",
    "Black Ward",
    "Blessing",
    "Blue Ward",
    "Consecrate Land",
    "Farmstead",
    "Green Ward",
    "Holy Armor",
    "Holy Strength",
    "Animate Artifact",
    "Lance",
    "Red Ward",
    "White Ward",
    "Power Leak",
    "Creature Bond",
    "Feedback",
    "Invisibility",
    "Flight",
    "Phantasmal Terrain",
    "Cursed Land",
    "Evil Presence",
    "Fear",
    "Paralyze",
    "Burrowing",
    "Unholy Strength",
    "Warp Artifact",
    "Weakness",
    "Earthbind",
    "Firebreathing",
    "Flashfires",
    "Shatter",
    "Tunnel",
    "Aspect of Wolf",
    "Instill Energy",
    "Lure",
    "Regeneration",
    "Tranquility",
    "Tsunami",
    "Wanderlust",
    "Web",
    "Wild Growth",
    "Armored Ascension",
    "Divine Verdict",
    "Indestructibility",
    "Lifelink",
    "Pacifism",
    "Convincing Mirage",
    "Solemn Offering",
    "Tempest of Light",
    "Essence Scatter",
    "Flashfreeze",
    "Ice Cage",
    "Negate",
    "Assassinate",
    "Deathmark",
    "Soul Bleed",
    "Ignite Disorder",
    "Entangling Vines",
    "Naturalize",
    "Oakenform",
    "Calming Licid",
    "Conviction",
    "Samite Blessing",
    "Smite",
    "Contempt",
    "Gliding Licid",
    "Corrupting Licid",
    "Death Stroke",
    "Mogg Infestation",
    "Torment",
    "Convulsing Licid",
    "Flowstone Blade",
    "Tempting Licid",
    "Aerial Modification",
    "Caught in the Brights",
    "Decommission",
    "Ice Over",
    "Gremlin Infestation",
    "Siege Modification",
    "Lightwheel Enhancements",
    "Roadside Assistance",
    "Flood the Engine",
    "Guidelight Optimizer",
    "Crash and Burn",
    "Skycrash",
    "Plow Through",
    "Silken Strength",
    "Ticket Tortoise"
],
    forceBannedCards: [],
    legalSets: [
    "Adventures in the Forgotten Realms",
    "Aether Revolt",
    "Aetherdrift",
    "Alara Reborn",
    "Alliances",
    "Amonkhet",
    "Antiquities",
    "Apocalypse",
    "Arabian Nights",
    "Assassin's Creed",
    "Avacyn Restored",
    "Battle for Zendikar",
    "Betrayers of Kamigawa",
    "Bloomburrow",
    "Born of the Gods",
    "Champions of Kamigawa",
    "Coldsnap",
    "Conflux",
    "Core Set 2019",
    "Core Set 2020",
    "Core Set 2021",
    "Dark Ascension",
    "Darksteel",
    "Dissension",
    "Dominaria",
    "Dominaria: United",
    "Dragon's Maze",
    "Dragons of Tarkir",
    "Duskmourn: House of Horror",
    "Edge of Eternities",
    "Eldritch Moon",
    "Eventide",
    "Exodus",
    "Fallen Empires",
    "Fate Reforged",
    "Fifth Dawn",
    "Final Fantasy",
    "Future Sight",
    "Gatecrash",
    "Guildpact",
    "Guilds of Ravnica",
    "Homelands",
    "Hour of Devastation",
    "Ice Age",
    "Ikoria: Lair of Behemoths",
    "Innistrad",
    "Innistrad: Crimson Vow",
    "Innistrad: Midnight Hunt",
    "Invasion",
    "Ixalan",
    "Journey into Nyx",
    "Judgment",
    "Kaladesh",
    "Kaldheim",
    "Kamigawa: Neon Dynasty",
    "Khans of Tarkir",
    "Legends",
    "Legions",
    "Limited Edition Beta",
    "Lorwyn",
    "Magic 2010",
    "Magic 2011",
    "Magic 2012",
    "Magic 2013",
    "Magic 2014",
    "Magic 2015",
    "Magic Origins",
    "March of the Machine",
    "March of the Machine: The Aftermath",
    "Mercadian Masques",
    "Mirage",
    "Mirrodin",
    "Mirrodin Besieged",
    "Modern Horizons 2",
    "Morningtide",
    "Murders at Karlov Manor",
    "Nemesis",
    "New Phyrexia",
    "Oath of the Gatewatch",
    "Odyssey",
    "Onslaught",
    "Outlaws of Thunder Junction",
    "Phyrexia: All Will Be One",
    "Planar Chaos",
    "Planeshift",
    "Prophecy",
    "Ravnica Allegiance",
    "Ravnica: City of Guilds",
    "Return to Ravnica",
    "Rise of the Eldrazi",
    "Rivals of Ixalan",
    "Saviors of Kamigawa",
    "Scars of Mirrodin",
    "Scourge",
    "Shadowmoor",
    "Shadows over Innistrad",
    "Shards of Alara",
    "Streets of New Capenna",
    "Strixhaven: School of Mages",
    "Stronghold",
    "Tarkir: Dragonstorm",
    "Tempest",
    "The Brothers' War",
    "The Dark",
    "The Lord of the Rings: Tales of Middle-earth",
    "The Lost Caverns of Ixalan",
    "Theros",
    "Theros Beyond Death",
    "Throne of Eldraine",
    "Time Spiral",
    "Torment",
    "Urza's Destiny",
    "Urza's Legacy",
    "Urza's Saga",
    "Visions",
    "War of the Spark",
    "Weatherlight",
    "Wilds of Eldraine",
    "Worldwake",
    "Zendikar",
    "Zendikar Rising"
],
    cashPrize: "50.00"
};

// ⭐ MAKE IT GLOBALLY ACCESSIBLE ⭐
if (typeof window !== 'undefined') {
    window.GAUNTLET_CONFIG = GAUNTLET_CONFIG;
        }
